### ISSUE TITLE
Specify starting track gain

### ISSUE THREAD

**Issue by trevordixon** [naomiaro/waveform-playlist#10]
I'd like to be able to specify gain when loading a track:

    playlist.load([
      {src: 'drums.mp3', gain: 0.5}
    ])

Is something similar already possible?

**Comment by naomiaro** [comment]
Hey! No currently it is not implemented but I have thought about doing this in the past. I can add this to the project since I think it would be good for initial mix settings.

**Comment by trevordixon** [comment]
Cool, thank you! Also, I noticed that `track.setGainLevel` doesn't update the UI's slider controller.

**Comment by naomiaro** [comment]
Ah OK, I'll take a look at that as well while I'm at it.
