### ISSUE TITLE
AudioBuffer as source?

### ISSUE THREAD

**Issue by Catsvilles** [naomiaro/waveform-playlist#100]
Is it possible to use buffer as src rather than a link? Any tips on how could I achieve that are highly appreciated! :)

**Comment by faroit** [comment]
you can read from a blob, as I've done here

https://github.com/sigsep/open-unmix-demo-electron/blob/master/src/components/player/player.js#L47

if you really want to  load from an audio buffer, its probably quite easy to extend waveform-playlist:

https://github.com/sigsep/open-unmix-demo-electron/blob/master/src/components/player/player.js#L47

**Comment by Catsvilles** [comment]
@faroit Yeah, just passing a blob saved my problem. Thank you very much! :)
