### ISSUE TITLE
Cursor & Track headers & Selections Don't Show / toggleActive Error In Angular 7

### ISSUE THREAD

**Issue by ewwwgiddings** [naomiaro/waveform-playlist#102]
Hi,

I am using this with Angular 7. I have everything working, except a few visual elements.

The track titles do not render. The cursor that shows track progress does not render. When I use the option to select a region (which does not change to the proper cursor when I do) the region is selected functionality wise cause I can loop it, but the area is not showing as selected.

I am using Bootstrap 4 SCSS could that be the problem? Does this only rely upon Bootstrap 3 CSS?

Also when I attempt to use the toggleActive function it gives me the error:
`TypeError: Cannot read property 'querySelectorAll' of undefined
    at toggleActive` where toggleActive is:
`
function toggleActive(node) {
      const active = node.parentNode.querySelectorAll('.active');
      let i = 0;
      const len = active.length;
      for (; i < len; i++) {
        active[i].classList.remove('active');
      }
      node.classList.toggle('active');
    }
`

Any idea how to fix any of this stuff?

Thank you,
Eric

**Comment by ewwwgiddings** [comment]
If anyone else struggles with this aspect:

1. Put "node_modules/waveform-playlist/styles/playlist.scss" into your angular.json styles and not in the component's scss
2. And for the toggleActive(this) the this in Angular is pointed to the regular scope of this so you need to pass it the actual element not a reference to "this" because of scoping issues
3. Also change node in the function to be node[0].whatever

**Comment by marcomancio** [comment]
@ewwwgiddings I should implement this library just for angular 7. 
Can I ask you how you managed to implement it in the Angular component?
I should show in the component a list of waves, with relative functions(play, stop, mute, etc..), but i just can't show them.
