### ISSUE TITLE
Usage Question

### ISSUE THREAD

**Issue by Pelican104** [naomiaro/waveform-playlist#105]
Hi, amazing project.
Here is what is most likely a dozy noob question...
Does this require NODE? 
If I download https://github.com/naomiaro/waveform-playlist/tree/gh-pages should that run on a LAMP server?
I seem to get a 500 Internal server error from waveform-playlist.var.js
Thanks

**Comment by naomiaro** [comment]
It needs some kind of a webserver running if you're requesting audio files, otherwise there will be permission errors. If you're working with local files, you can drop them to upload them in the browser only like this example http://naomiaro.github.io/waveform-playlist/newtracks.html
