### ISSUE TITLE
Examples working in Safari

### ISSUE THREAD

**Issue by glumac** [naomiaro/waveform-playlist#110]
[Example pages](http://naomiaro.github.io/waveform-playlist/stem-tracks.html ) do not work in Safari.

[Error] TypeError: this.ac.createStereoPanner is not a function. (In 'this.ac.createStereoPanner()', 'this.ac.createStereoPanner' is undefined)
	setUpSource (waveform-playlist.var.js:7952)
	schedulePlay (waveform-playlist.var.js:5860)
	(anonymous function) (waveform-playlist.var.js:2375)
	forEach
	play (waveform-playlist.var.js:2373)
	(anonymous function) (waveform-playlist.var.js:1903)
	emit (waveform-playlist.var.js:1223)
	(anonymous function) (emitter.js:128)
	dispatch (jquery-2.1.4.min.js:3:6472)
	(anonymous function) (jquery-2.1.4.min.js:3:3247)

**Comment by naomiaro** [comment]
What version of Safari are you using @glumac ?
I have version 13 and it looks OK there. I should check later on Safari 9 I have hanging around on an older macbook air.

**Comment by jammmet** [comment]
Same error on Safari 13.0.1

**Comment by Zegorax** [comment]
I have the same problem using Safari 13.2 (Technology Preview) and 13.0.5

**Comment by k-ljung** [comment]
Any updates? I have the same issue in Safari,  both desktop and Mobile Safari.

**Comment by vasinl124** [comment]
what I did is to use this function instead
// this.panner = this.ac.createStereoPanner();
    this.panner = this.ac.createPanner();

**Comment by scrawlon** [comment]
Building on @vasinl124's suggestion, I was able to get the examples running in Safari 13.1 with the following changes to Playout.js:

```JavaScript
this.panner = this.ac.createStereoPanner !== undefined 
    ? this.ac.createStereoPanner() : this.ac.createPanner();
```

```JavaScript
  setStereoPanValue(value) {
    if (this.panner) {
      const pan = value === undefined ? 0 : value;

      if ( this.panner.pan !== undefined ) {
        this.panner.pan.value = pan;
      } else {
        this.panner.panningModel = 'equalpower';
        this.panner.setPosition(pan, 0, 1 - Math.abs(pan));
      }
    }
  }
```

It doesn't look like Safari supports createStereoPanner yet: [https://caniuse.com/#search=createStereoPanner](https://caniuse.com/#search=createStereoPanner )

**Comment by naomiaro** [comment]
Thanks @scrawlon for the PR!
