### ISSUE TITLE
Set cursor position with an event

### ISSUE THREAD

**Issue by eugenz3rr** [naomiaro/waveform-playlist#119]
Hi,
I've an usecase where I want to set the cursor with a slider, which is more accurate and pleasent for the user to pinpoint the exact location.

I've added a small patch to update the cursorposition.

**Comment by eugenz3rr** [comment]
[119-set-cursor-position.txt](https://github.com/naomiaro/waveform-playlist/files/4565312/119-set-cursor-position.txt)

**Comment by naomiaro** [comment]
You can use the `select` event for this

`ee.emit("select", startTime, endTime);`
