### ISSUE TITLE
Stereo Panner example audio tracks aren't panned.

### ISSUE THREAD

**Issue by scrawlon** [naomiaro/waveform-playlist#120]
The [Stereo Panner example](http://naomiaro.github.io/waveform-playlist/stereopan.html) audio tracks aren't panned. I was able to fix this in 'stereopan.js' by changing the 'stereopan' key to 'stereoPan':

```JavaScript
    {
      name: 'Left Panned Track',
      src: 'media/audio/PianoSynth30.mp3',
      stereoPan: -1,
    },
    {
      name: 'Right Panned Track',
      src: 'media/audio/BassDrums30.mp3',
      stereoPan: 1,
    },
```

Simple fix. Pull request to come.

**Comment by naomiaro** [comment]
Thanks for the fix!
