### ISSUE TITLE
Is there a limit of how many tracks that can be opened at once?

### ISSUE THREAD

**Issue by dennisski** [naomiaro/waveform-playlist#125]

**Comment by naomiaro** [comment]
The limit around webaudio still is with the amount of memory your tracks are using once decoded. It will depend on track length as well as number of tracks. At some point I've been meaning to try alternative ways of somehow streaming sound through the graph without previously decoding the audio to sample level, but I'm not sure how synchronisation would work with more than one track when doing that.
