### ISSUE TITLE
Hide or collapse Tracks

### ISSUE THREAD

**Issue by dennisski** [naomiaro/waveform-playlist#134]
I was wondering if there was a way to hide or collapse tracks on the fly. When working with multiple tracks, having to scroll up or down to work with solo positioning etc. has been very difficult and clumsy at times.

**Comment by faroit** [comment]
I think this is related to #32, #35 and #46: modifying the playlist.tracks does not automatically re-render the player.
@naomiaro I guess you wanted to find a clean solution but maybe a short-term "hacky" approach could be sufficient?

**Comment by naomiaro** [comment]
Yes I really should look into doing something for this at some point coming up @faroit . I had started to modernise the codebase for this project, but then that got derailed last year with covid. I think it could make sense to release some functionality like that on this code base first and a few other low hanging fruit, then try to continue the more modernised version afterwards.

**Comment by dennisski** [comment]
I am really happy you finally responded. If you are updating the code maybe you can add some effects like reverb or Gain or EQ? Using something like sox or ffmpeg? This DAW has been so wonderful for what we use it for.

**Comment by naomiaro** [comment]
Out of curiosity, how to you use waveform-playlist @dennisski ?

**Comment by dennisski** [comment]
We record tracks online using mediarecorder code. and since there are some latencies in browsers we use your code Waveform Playlist to review and get multiple tracks in correct sync with each other.  We have to use other methods to get effects at the moment.

**Comment by dennisski** [comment]
Here is a link to a video that shows how we use Waveform-playlist to sync multiple tracks. https://bandhug.com/watch/older-video-on-daw-adjustment-and-adding-second-to-bt_ilTydlUCWR9cXFJ.html

**Comment by naomiaro** [comment]
Thanks for this, very interesting video! Seems like there could be a use to place a marker on each track which then could be used as a sync point. Especially then if tracks have a few alignment metronome clicks recorded at the beginning.

**Comment by dennisski** [comment]
Yes a marker would definitely help with auto sync

**Comment by naomiaro** [comment]
I've had a first go at updating a bunch of things and adding a collapse/remove track option to the controls.

https://naomiaro.github.io/waveform-playlist/stem-tracks.html

I released it at 4.0.0 since now it's using Bootstrap 4, Fontawesome 5, and jQuery 3.
