### ISSUE TITLE
【Fixed】seems to be a bug with references, or I'm missing something.

### ISSUE THREAD

**Issue by zhinian1994** [naomiaro/waveform-playlist#135]
renderControls(note, i) {
    //seems to be a bug with references, or I'm missing something.//fixed
    const that = this;
    return this.controls.map(ctrl =>
      h(`i.${ctrl.class}`, {
        attributes: {
          title: ctrl.title,
        },
        onclick: () => { 
          ctrl.action(note, i, that.annotations, { 
            linkEndpoints: that.playlist.linkEndpoints,
          });
          this.length = this.annotations.length;
          this.resizeHandlers = []; //clear this.resizeHandlers , thanks for your sharing ~。~
          this.setupInteractions();
          //this.setupEE(that.playlist.ee);
          that.playlist.drawRequest();
        },
      }),
    );
  }

**Comment by naomiaro** [comment]
Did you find a bug somewhere here? I'm not sure what this issue is about, so I will close this for now. Feel free to reopen though if there's an issue with the annotations still.
