### ISSUE TITLE
Rendering bug when trimming track on device with devicePixelRatio > 1

### ISSUE THREAD

**Issue by delewis13** [naomiaro/waveform-playlist#137]
To reproduce:

(1) Use Full Waveform Editor demo
(2) Upload long track [e.g. 3 minutes]
(3) Select relatively large section of track [e.g. ~1 minute worth, enough to span at least 2 canvas]
(4) Trim
(5) Observe that leftmost canvas has a rendering bug where it is only seeing the top half [see screenshot]

Attempted fix:

Hard-coded `scale` on line 408 of Track.js to `1`. This seemed to solve the issue, though I don't know what other ramifications it has.

<img width="935" alt="Screen Shot 2021-02-04 at 10 59 39 pm" src="https://user-images.githubusercontent.com/20104413/106889944-d1c55000-673c-11eb-8fb4-a326004c27d0.png">

Environment:

- Chrome 88

**Comment by QTimort** [comment]
I don't know if this the same issue as in https://github.com/naomiaro/waveform-playlist/issues/131 but if that's the case, then this how we fixed it. We added a scale member field to Track.js https://github.com/nartj/waveform-playlist/blob/56b8427336fa743edf6b9fee2a013d1723a70254/src/Track.js#L556 and decide to force to re render if the scale changed https://github.com/nartj/waveform-playlist/blob/master/src/render/CanvasHook.js#L27

**Comment by naomiaro** [comment]
Thanks for reporting this, I'll try to fix this in the project soon!
