### ISSUE TITLE
Same audio file is showing different duration in firefox and chrome

### ISSUE THREAD

**Issue by siddharth-koolioai** [naomiaro/waveform-playlist#139]
firefox - 
![firefox](https://user-images.githubusercontent.com/62323129/107876099-d41c6c80-6ee9-11eb-999f-3ae4c79e9301.jpg)
chrome -
![chrome](https://user-images.githubusercontent.com/62323129/107876102-db437a80-6ee9-11eb-9abe-0c876c626a6d.jpg)

**Comment by naomiaro** [comment]
These kind of bugs would be to do with the audio decoders each browser used. Before I've filed bugs straight into the browser projects.
