### ISSUE TITLE
Change master volume?

### ISSUE THREAD

**Issue by utjduo** [naomiaro/waveform-playlist#14]
Hi again! I'm wondering if there is a way to change the master volume of the loaded tracks?
Thanks!

**Comment by naomiaro** [comment]
Hi! No currently there is no other gain node for adjusting the volume of the mix before it's sent to your speakers. That could be a good feature to have though.

**Comment by Willena** [comment]
Maybe it is not the best solution, but this functionality was important to me, so I have written something that do what I want. Let me know what you think about it.

**Comment by naomiaro** [comment]
I've updated some variable names and included documentation in the readme for the new support. All volume changes can be seen [here](http://naomiaro.github.io/waveform-playlist/stem-tracks.html)
