### ISSUE TITLE
Click selection bug when "isAutomaticScroll" set TRUE

### ISSUE THREAD

**Issue by pastyle** [naomiaro/waveform-playlist#140]
When there is a scroll bar and we click to select a section near the end of the sound, the cursor is repositioned to the beginning.

This happens when the audio is greater than the width of the container and the option "isAutomaticScroll" is set to TRUE.

![full-waveform-editor](https://user-images.githubusercontent.com/43682856/115300140-fd4db900-a135-11eb-9d48-fbb87b9e6ddb.gif)

**Comment by faroit** [comment]
yes, I've noticed this as well. @naomiaro do you have a hint of how to fix this?

**Comment by naomiaro** [comment]
Looking into it now, thanks for reporting :)
