### ISSUE TITLE
Slice, cut tracks into multiple parts.

### ISSUE THREAD

**Issue by Catsvilles** [naomiaro/waveform-playlist#149]
Hello everyone, has anyone been working on such functionality? Any advice, guidance, examples on what would be the right way to approach this? Ready to take on this and share my results in case I will be able to crack it.

**Comment by Catsvilles** [comment]
@naomiaro Hi, I'm ready to take on this and PR, so any hints on where to look into are highly appreciated :)

I think to implement first the rendering of a multiple audiobuffers on the same track, since once sliced users should be able to move the parts of the audio around, and possibly delete them. Once multiple audiobuffers are implemented, slicing should be easy enough, since we have Trim functionality anyway. Does that makes any sense?

**Comment by KnifeFed** [comment]
Did you get anywhere with this?
