### ISSUE TITLE
Best place to ask questions?

### ISSUE THREAD

**Issue by rowild** [naomiaro/waveform-playlist#157]
Hi!

I know that github is not the best place to ask question, but I did not find a a recommendation in the readme. Any chance to let us what's the best place?

I am researching for a university project, where one requirement is to be able to zoom into the wave down to the point where you can see a single impuls (so-to-say, I hope you know what I mean). The API has a zoom in setting, if I'm not mistaken, but I wonder, what is the impact of adding many, many zoom stages? Is there any kind of aspect to be taken into consideration like performance? Does waveform-playlist draw wavelines for each and every zoom level, which would result in maybe very, very much data to manage?

Any advise would be most welcome! Thank you!

**Comment by naomiaro** [comment]
I've just turned this on for the repository: https://github.com/naomiaro/waveform-playlist/discussions
