### ISSUE TITLE
No styles after initializing the player

### ISSUE THREAD

**Issue by marco910** [naomiaro/waveform-playlist#160]
I installed the package with NPM and added it to my page as in the documentation. However, I don't have any styles like here: http://naomiaro.github.io/waveform-playlist/stationarytrack.html

Why is that?

**Comment by naomiaro** [comment]
You have to include the original `scss` that's at `styles/playlist.scss` within the installed module.

**Comment by naomiaro** [comment]
The examples are also including bootstrap for their specific buttons, but that isn't necessarily required if you define/design your own controls.

**Comment by marco910** [comment]
The custom buttons haven't been the problem. 

The problem is that the styles of each track (mute/solo button, etc.) are crashed.
I also included the stylesheet which is also being loaded.

**Comment by naomiaro** [comment]
The mute/solo buttons in the examples are also just using styles from Bootstrap. Sometime I could include a base css for buttons, but atm it doesn't exist.

**Comment by marco910** [comment]
> The mute/solo buttons in the examples are also just using styles from Bootstrap. Sometime I could include a base css for buttons, but atm it doesn't exist.

That would be great!

**Comment by naomiaro** [comment]
Yes I really should make the minimal example not use Bootstrap and have it truly minimal 😀

**Comment by marco910** [comment]
@naomiaro Please try to not use Bootstrap in the background because when someone doesn't use Boostrap for his site it could crash other styles when using the same classes.

**Comment by stuhops** [comment]
Please add bootstrap as a requirement in the README because I just wasted a bunch of time googling around. Thanks for the good work!

**Comment by naomiaro** [comment]
Release 4.0.4 should fix this.
