### ISSUE TITLE
download question

### ISSUE THREAD

**Issue by xiaoLongXD** [naomiaro/waveform-playlist#172]
![image](https://user-images.githubusercontent.com/44644539/129659355-56eee279-9aff-49e9-8b43-7865a6b5eb94.png)
when i run ee.emit('startaudiorendering', 'wav')
throw this error
and  function initExporter does not seem to be called
![image](https://user-images.githubusercontent.com/44644539/129659606-b3bda63d-4eb4-44b6-b8e5-320292cb076f.png)

How should I solve this problem
Thank you.

**Comment by naomiaro** [comment]
Hello! After you create the playlist you have to call this function if you want to use recording:

https://github.com/naomiaro/waveform-playlist/blob/main/ghpages/js/record.js#L38

**Comment by xiaoLongXD** [comment]
thanks for prompt reply.

**Comment by xiaoLongXD** [comment]
thanks for prompt reply.

**Comment by xiaoLongXD** [comment]
thanks for prompt reply.
