### ISSUE TITLE
Is there a way to reset/clear the playlist ?

### ISSUE THREAD

**Issue by d4guru** [naomiaro/waveform-playlist#18]
Hello, I'm using your library since today and I have to say you have done a great job !
Just Im wondering how do I reset de playlist ? I need to remove all the tracks before adding new ones.

something like `playlist.removeAll()` or `playlist.clear()`

Thanks in advance

Lorenzo

**Comment by naomiaro** [comment]
There's no method specifically for that as of now, but you could write something like `playlist.tracks = []` to work around this until a better way has been added.

**Comment by faroit** [comment]
I just came up with the same wish as @d4guru... just want to report that the proposed quickfix from @naomiaro works, but users need to take about the tracks that are currently being played. If you load new tracks without stopping the old first, you are getting in trouble of playing both lists. Also you cannot easily stop the old playlist then.

**Comment by faroit** [comment]
I think this is not fully fixed, clearing the playlist should also reset the `soloedTracks` and `mutedTracks` array so that new tracks. Does this make sense?

**Comment by naomiaro** [comment]
aha totally @faroit ... def implemented this too quickly! Thanks, I will make a patch.
