### ISSUE TITLE
Is there a way to save/load a recording session? 

### ISSUE THREAD

**Issue by MartinBarker** [naomiaro/waveform-playlist#180]
Hello, I'm trying out waveform-playlist as an audacity replacement and was wondering if there was any way I could save a recording sessions without exporting all the individual recording files?

For example; record some audio, close the page, and when the page is re-opened, load the previous recording sessions seamlessly. 

Can I save and export the recording sessions as some sort of smaller file? Or save the recording audio contents as a cookie in the webpage or local variable of some sorts?

Thanks

**Comment by naomiaro** [comment]
Right now the save/restore functionality would need to be implemented. The wav contents would need to be properly stored somewhere. Neither cookies nor localstorage would be suitable for this type of data. I don't think there exists anything suitable on the client only to store this type of data for later use if the page is closed. Some type of backend would be the best option here.
