### ISSUE TITLE
Uncaught TypeError: Cannot set property 'onblur' of null (this.ctrls["audio-start"])

### ISSUE THREAD

**Issue by alemangui** [naomiaro/waveform-playlist#2]
Hello,

I stumbled upon this error (Chrome v.44) when trying out the [minimal example](http://naomiaro.github.io/waveform-playlist/examples/minimal.html), which blocked me from interacting with the demo.

After a quick glance in the console, this seems to be the line causing it:
```
this.ctrls["audio-start"].onblur = this.validateCueIn.bind(this);
```
For info, all elements inside ```this.ctrls``` are null as well.

Cheers!

**Comment by naomiaro** [comment]
Thanks! I can fix this shortly...
