### ISSUE TITLE
Hi,I'm having trouble with your project!

### ISSUE THREAD

**Issue by eunion** [naomiaro/waveform-playlist#20]
When I load greater than 50M of MP3, the browser page on the collapse of the Ben！

**Comment by naomiaro** [comment]
I don't think web audio is super great with huge files currently, as your browser needs enough memory to have these files decoded. I was thinking of experimenting with a way to have pre-rendered peaks and to stream and audio element through the web audio system, but I haven't had time to experiment with this currently. I'm not sure how timing would end up with multi tracks loaded through <audio> elements

**Comment by Willena** [comment]
It is not very dificult to build pre-rendered peaks and use these data. 
[This](https://github.com/bbc/audiowaveform) project hosted on github can help us to generate small files that correspond to audio peaks. The most dificult part is to stream audio instead of download the whole file.

**Comment by naomiaro** [comment]
Yes, I wanted the peaks data to be compatible with output from those BBC projects. For streaming audio I was thinking about checking out this https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaElementSource

**Comment by Willena** [comment]
I have heard of https://developer.mozilla.org/fr/docs/Web/API/AudioContext/createMediaStreamSource but don't really know if it can work here. Maybe it needs some experiments. 
In fact don't really like the idea of creating multiple html audio elements, but may be it is the best way to do it...

**Comment by naomiaro** [comment]
Yeah I was going to check it out pretty much because I thought it would be the easiest way to integrate this functionality if it does work. I don't know if it would work timing wise with multiple audio elements though. Can experiment with that in a bit.

**Comment by mbarsocchi** [comment]
Just for your info, I have similar problem and I'm working on a chunked solution: a php script returns only sub-part of the entire mp3 file, this for example returns initial part:

`$handle = fopen($filename, 'r');  
$content = fread($handle, filesize($filename));  

$length = strlen($content);  

if (!$session->IsLoggedIn()) {  
    $length = round(strlen($content) / 10); /* Change 10 to be 2 to play 50% of the song, or 5 to play 20% of the song. A value of 10 will play 10% of the song, a decent preview amount */  
    $content = substr($content, $length * .66 /* Start extraction 2/3 of that in; if it does turn out to be 30 seconds, it will start 20 seconds in.*/, $length);  
}  

header("Content-Type: {$id3_info['mime_type']}");  
header("Content-Length: {$length}");  
print $content; `

with some more code and an event listener on zoom in/out maybe is it possible to scrool and edit a big file.

**Comment by naomiaro** [comment]
More work in general will need to be done on using large files with the webaudio api.

**Comment by ptrkcsk** [comment]
[phonograph](https://github.com/Rich-Harris/phonograph) is a cool project designed to make it possible to use the Web Audio API with large files.

From their README:

> **The problem**
> 
> You've read about the Web Audio API, in particular the AudioBuffer, which seems like it might be useful except for the bit that says it's 'designed to hold small audio snippets, typically less than 45s'. And they're not kidding about that – not only do you have to fetch the entire file before you can play it, but you have to have enough spare RAM to store the uncompressed PCM data (aka .wav – typically ten times the size of the source .mp3) otherwise the browser will crash instantly.

> **The solution**
> 
> By breaking up the data into small chunks, we can use `decodeAudioData` to create a few seconds of PCM data at a time, making it very unlikely that we'll crash the browser. We can then play a short chunk, swapping it out for the next chunk (with a bit of overlap to avoid audible glitches) when ready.
> 
> By using the `fetch()` API, we can stream the data rather than waiting for the whole file to load.

There are still some significant caveats, but it looks promising.

**Comment by Micrufun** [comment]
For audio streaming, is HLS a feasible option? HLS has been standardized as [RFC 8216](https://datatracker.ietf.org/doc/html/rfc8216).

* Is HLS intended only for video, not audio?
* Does HLS work with web audio API?
* ...

### Reference

https://developer.mozilla.org/en-US/docs/Web/Media/Streaming

https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Live_streaming_web_audio_and_video
