### ISSUE TITLE
Sound is not audible after smaller length audio is finished in nextJS app

### ISSUE THREAD

**Issue by QuratFatima906** [naomiaro/waveform-playlist#201]
I cloned the NextJS example project and trying to play two audios of different length, as soon as the marker cross the end of smaller audio, the other audio goes on mute.

I tried debugging and none of these events is triggered: mute, pause, stop, finished.

It is working fine [here]( http://naomiaro.github.io/waveform-playlist/newtracks.html) if I choose same files.

My best guess is that volume or gain is set to zero somehow but couldn't catch it. Any leads?

**Comment by naomiaro** [comment]
Is the code using the latest version of the app? This was a bug in older versions of the library.

**Comment by QuratFatima906** [comment]
I was using 4.2.1, Just updated. It's resolved, Thank you.
