### ISSUE TITLE
Solo/Mute not obeyed on seek

### ISSUE THREAD

**Issue by slimchandi** [naomiaro/waveform-playlist#21]
Noticing a new problem which isn't resolved by updating to latest version.

The solo and mute buttons work fine until I seek to a new part, when all the audio is heard as if no buttons are depressed. If I pressed Solo on track 1, once I seek all tracks are heard again, even though that button will still appear depressed on the screen. Same true for mute. Track volumes appear to function normally and persist after seeking

http://www.chorosemvoce.com/ for an example. Can anyone replicate this?

**Comment by Willena** [comment]
Sorry but I can't reproduce it.
Can you give me the exact list of actions so that I can try to reproduce it ? ( use the sample below )

1. click on mute on track 1
2. ...

**Comment by slimchandi** [comment]
Sorry, more detail. Using W7 SP1 and Chrome Version 53.0.2785.143 m

1. http://www.chorosemvoce.com/brejeiro.html
2. Click play
3. Solo track 1 (button depressed, only track 1 heard)
4. Seek into track by 20s
5. All tracks heard together (track 1 solo button still appears depressed).

Extra info: after seeking, if I then solo track 2, track 1 and 2 are heard only (which obeys what the track buttons say. Maybe the solo and mute parameters are being reset on seek, and pressing a solo button on any track then causes all the solo/mute buttons to be 'checked'.

1. Play
2. Solo 1 (only 1 heard)
3. Seek 20s in (all tracks heard)
4. Solo 2 (now 1 and 2 heard only)
5. Seek 20s in more (all tracks heard)

Hope this is clear?

**Comment by naomiaro** [comment]
I can't reproduce this issue on the same version of Chrome on MacOSX. I wonder if there's something different with a Windows version. Are you using a tablet?

**Comment by Willena** [comment]
I've tested with Firefox 50.0 beta, Chrome 53.0.2785.116, Win10 and every things is Okay.

**Comment by slimchandi** [comment]
OK I can't replicate it any more now! Very odd. Seems to function properly now, consider it closed! Thanks

**Comment by d4guru** [comment]
I have the same issue. Also when pause then play again all tracks muted will play. Then if I mute another track while playing the other muted tracks get muted again. Using chrome Version 49.0.2623.112 (64-bit) on macosx 10.7.5. 

When I log the playlist on play or pause I get this which seams to be correct.
`_class {tracks: Array[4], soloedTracks: Array[0], mutedTracks: Array[2], playoutPromises: Array[4], cursor: 0…}`

But when playing your example Willena everything is working.

**Comment by naomiaro** [comment]
@d4guru is this with the latest version? You can only recreate this with a playlist you've made, not one hosted in the examples?

**Comment by d4guru** [comment]
@naomiaro thanks for the fast reply. No more issue with the latest version. Thank you.

**Comment by naomiaro** [comment]
Awesome! Great to hear @d4guru ! @slimchandi did you upgrade versions recently, perhaps it was an older version that had been giving you problems?

**Comment by naomiaro** [comment]
I think the code that caused that issue was on the master branch, but it had not been bundled into a release.

**Comment by Willena** [comment]
It is quite strange, because I realize that I have tested with my edited fork ( based on the last commit in the master branch and with features described in the pull request ) and there are no problems at all...
