### ISSUE TITLE
Auto scrolling while playing

### ISSUE THREAD

**Issue by d4guru** [naomiaro/waveform-playlist#23]
Is there a way for the playlist to automatically scroll when the end of DIV is reached ?

_btw I don't know how to label an issue with the "question" label.._

**Comment by naomiaro** [comment]
Unfortunately not yet

**Comment by naomiaro** [comment]
This has now been added in the latest release!

Set playlist config:

```javascript
// Whether to automatically scroll the waveform while playing
isAutomaticScroll: true,
```

**Comment by mayadi1** [comment]
I am getting this error when I added isAutomaticScrool: true

emitter.js:5 Uncaught TypeError: Cannot read property 'getEventEmitter' of undefined
    at emitter.js:5

**Comment by mayadi1** [comment]
Cannot read property 'getBoundingClientRect' of null

**Comment by mayadi1** [comment]
isAutomaticScroll: true, does not work even in your guys demos :/

**Comment by mayadi1** [comment]
Okay Here is the fix to this: 
in Waveform=playlist.var.js:
from line 5128
When isAutomaticScroll = true, when the timeline is scrolled and when a "select" event is emitted to an anterior time, scroll does not update.

Here is the code to update below to fix.(in module 59)

Thank you

_createClass(_class, [{
key: 'hook',
value: function hook(node) {
var playlist = this.playlist;
if (!playlist.isScrolling) {
var el = node;
`      if (playlist.isAutomaticScroll && playlist.isPlaying()) {
          var rect = node.getBoundingClientRect();
          var cursorRect = node.querySelector('.cursor').getBoundingClientRect();

          if (cursorRect.right > rect.right || cursorRect.left < rect.left) { // Update is here
          //if (cursorRect.right > rect.right) {
            playlist.scrollLeft = playlist.playbackSeconds;
          }
        }

        var left = (0, _conversions.secondsToPixels)(playlist.scrollLeft, playlist.samplesPerPixel, playlist.sampleRate);

        el.scrollLeft = left;
      }
    }`

**Comment by naomiaro** [comment]
@mayadi1 what browser are you using this in? It works in the demos for me.

**Comment by naomiaro** [comment]
There is also this open bug for it when using the select event.

https://github.com/naomiaro/waveform-playlist/issues/59

**Comment by zhouhong** [comment]
try in this
if (playlist.isAutomaticScroll&&node.querySelector('.cursor')) {
	          var rect = node.getBoundingClientRect();

add the &&node.querySelector('.cursor') condition to ensure the node couldn't be null,it works fine for me now.
