### ISSUE TITLE
Effects

### ISSUE THREAD

**Issue by crowecawcaw** [naomiaro/waveform-playlist#24]
One thing that could be useful is if it were possible to add effects to tracks. I think it would be easy to add this functionality to the Track object. You could use a setEffects() method that would take an array of Web Audio nodes and connect them in the string of gain nodes that are currently used. If this sounds useful to other people too, I could write the code and do a PR.

**Comment by Willena** [comment]
Well that's not a bad idea !  I think it can be also interesting to create à small interface with à list of available/used  effects and their corresponding parameters.

**Comment by iooops** [comment]
Any update on this???

**Comment by joshuabenker** [comment]
any updates?;-)

**Comment by naomiaro** [comment]
Starting work on this

https://github.com/naomiaro/waveform-playlist/discussions/189
