### ISSUE TITLE
Avoid crash of Browser when load big mp3 file in js

### ISSUE THREAD

**Issue by mbarsocchi** [naomiaro/waveform-playlist#25]
When used with big file (**around 140Mb**) Chrome crash (and also FF). Is there a way to load big files? (maybe without waveform? or async paint waveform?)

**Comment by Willena** [comment]
Hi ! Isn't the same problem as #20 ?

**Comment by naomiaro** [comment]
Yeah it's the same problem. A problem with no clear solution using web audio purely it seems.
