### ISSUE TITLE
Usage with electron

### ISSUE THREAD

**Issue by maximelebastard** [naomiaro/waveform-playlist#26]
Hi,

I try to run the player in an electron (https://github.com/electron/electron) app. I encounter this issue, and I don't really understand what "worker!" means.

I just started a blank electron project, added the dependancy to your lib and paste your getting started code.

Do you have an idea of what I am missing ?

Here is the stack trace:

```
App threw an error during load
Error: Cannot find module 'worker!./track/recorderWorker.js'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/private/var/www/PickNinja/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/private/var/www/PickNinja/node_modules/waveform-playlist/lib/Playlist.js:47:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

**Comment by naomiaro** [comment]
There's a web worker running in the background for recording stuff here. I'm not to familiar with electron and don't know how it deals with web workers, so at this point unsure what to do about it.

**Comment by maximelebastard** [comment]
Thanks for your fast reply. It seems to be unsupported by electron https://github.com/electron/electron/issues/797  :(

As I don't need recording but just playing, is there a way to not require workers ?

**Comment by naomiaro** [comment]
I think it's saying there that web workers don't support node apis, but I'm not using any node apis there so I think it can work. How are you loading the project with electron? Did you change any of the file paths?

I want to refactor the project to have a plugin system for recording, exporting etc, but currently everything is all together so you would have to edit the code to remove the imports.

**Comment by maximelebastard** [comment]
I installed it with npm
`npm install waveform-playlist --save`

And my js script is this one:

```
'use strict';
const electron = require('electron');
const WaveformPlaylist = require('waveform-playlist');

const app = electron.app;

// adds debug features like hotkeys for triggering dev tools and reload
require('electron-debug')();

// prevent window being garbage collected
let mainWindow;

function onClosed() {
	// dereference the window
	// for multiple windows store them in an array
	mainWindow = null;
}

function createMainWindow() {
	const win = new electron.BrowserWindow({
		width: 600,
		height: 400
	});

	win.loadURL(`file://${__dirname}/index.html`);
	win.on('closed', onClosed);

	loadWaveform();

	return win;
}

app.on('window-all-closed', () => {
	if (process.platform !== 'darwin') {
		app.quit();
	}
});

app.on('activate', () => {
	if (!mainWindow) {
		mainWindow = createMainWindow();
	}
});

app.on('ready', () => {
	mainWindow = createMainWindow();
});

function loadWaveform() {
	var playlist = WaveformPlaylist.init({
		samplesPerPixel: 3000,
		mono: false,
		waveHeight: 70,
		container: document.getElementById("playlist"),
		state: 'cursor',
		colors: {
			waveOutlineColor: '#E0EFF1',
			timeColor: 'grey',
			fadeColor: 'black'
		},
		controls: {
			show: true,
			width: 200
		},
		zoomLevels: [500, 1000, 3000, 5000]
	});

	playlist.load([
		{
			"src": "media/audio/batterie.mp3",
			"name": "Drums",
		},
		{
			"src": "media/audio/Guitare Lead.mp3",
			"name": "GLead",
		},
    {
      "src": "media/audio/Guitare rythm D.mp3",
      "name": "GRythmD",
    },
	]).then(function() {
		//can do stuff with the playlist.
	});
}
```

**Comment by naomiaro** [comment]
hmm this might be fixed in a newer version of the web worker loader (0.7.1). I can try upgrading to that and making a new release to see if it helps.

https://github.com/webpack/worker-loader/pull/16

**Comment by naomiaro** [comment]
I could maybe even just inline the workers for now as well, I think that could help solve some issues for sure.

**Comment by naomiaro** [comment]
There's a version 2.4.1 to try with those changes. Delete your node_modules folder to try a fresh install. It would be really cool if this could work with electron, so I'd like to look into this more if that doesn't help.

**Comment by naomiaro** [comment]
This worker-loader is for webpack, I wonder if it would be fine if you install webpack as a dependency. I should break the dependency on webpack if this is the case...

**Comment by naomiaro** [comment]
I can try this perhaps

https://github.com/systemjs/systemjs/issues/913

**Comment by naomiaro** [comment]
Installing version 2.4.2, you should have no problems including waveform-playlist into an electron project. It will require some more work from just minimal.html since 'document' is not available there as I have found out in my test electron project. If you get farther with the setup of an electron minimal.html example, would be cool to hear!

**Comment by maximelebastard** [comment]
It loads well, thank your for this fast and efficient help @naomiaro !

**Comment by naomiaro** [comment]
great to hear @maximelebastard ! If you encounter any other problems with the lib, def open some more issues 👊
