### ISSUE TITLE
Exclusive Solo / Radio Solo / Shift+solo function

### ISSUE THREAD

**Issue by faroit** [naomiaro/waveform-playlist#27]
Just want to thank you for this great project. It is very helpful for us and we want to deploy on a [public website](https://sisec.inria.fr) where we want to display results for audio source separation. In source separation you normally listen to individual tracks of a mixture and want to switch to these tracks with a click of a button.

In Audacity you can do this by holding shift and click on the solo buttons. This basically toggles `soloed` on one track an disables it on all other tracks.

The best fit for a corresponding user interface would be a radio button, where only one option is allowed to be active a the same time.

So my feature proposal would be to add a `radiosolo` option to each track that would display a third button which allows to toggle between the tracks.

**Comment by naomiaro** [comment]
Would you want the radio button @faroit or if I make key controls work, would that be better?

**Comment by faroit** [comment]
Here is a use case for radio buttons: https://www.audiolabs-erlangen.de/resources/2016-ICASSP-COMMONFATE

I think thats intuitive to use. 

Additionally it would make send to expose events in the api to make custom controls for `mute`, `solo`, `radiosolo` etc...

**Comment by faroit** [comment]
this works now. thanks!
