### ISSUE TITLE
loadprogress event should fire if all sources are loaded

### ISSUE THREAD

**Issue by faroit** [naomiaro/waveform-playlist#29]
Another day, another proposal ;-)

Currently the `ee.on('loadprogress')` emits the individual load progress of each source. I am rather interested in general loading indicator that fires when all sources are loaded. 

maybe `.on('finishedLoading')` ?

**Comment by naomiaro** [comment]
haha keep them coming! 😁  
Yes I really should add some event like this for ease of use...
