### ISSUE TITLE
Use react

### ISSUE THREAD

**Issue by domachine** [naomiaro/waveform-playlist#3]
Hey,

Pretty cool project which provides a lot of inspiration. Have you ever thought about using react to render the UI? I'm coming from a strong react background. So I'm wondering, why you're going the painful way of rendering all this manually? Just out of curiosity.

Regards

**Comment by naomiaro** [comment]
Hey, yeah the master branch is still based from 2013... but totally am heading that direction. If you check out the ES6 branch I'm using https://github.com/Matt-Esch/virtual-dom to render. Just need to finish a couple things...

**Comment by domachine** [comment]
Ah ok I see. Let me know if you need and keep up the great work :+1:

**Comment by naomiaro** [comment]
Newer code using virtual dom is now on master if you wanted to check it out.
