### ISSUE TITLE
Issues with export to WAV function

### ISSUE THREAD

**Issue by ezimmert** [naomiaro/waveform-playlist#33]
Hi,
I'm playing with the full editor demo (online and dist folder) and I can't get the export to WAV function to work. Console shows "TypeError: Cannot read property 'postMessage' of undefined".

Any fix for the same?

Thanks in advance

Emmanuel

**Comment by naomiaro** [comment]
Hey I'll check into this, could have been a problem introduced when I was removing webpack dependencies.

**Comment by naomiaro** [comment]
Hey, I've changed how the exporter was initialized, but didn't update demos or docs. Add this to your code if you want a worker to export.

`playlist.initExporter()`

I will update the docs.

**Comment by ezimmert** [comment]
Thanks for your prompt answer, it works like a charm!
