### ISSUE TITLE
customClass not included in `npm i` lib code, version 2.6.1

### ISSUE THREAD

**Issue by alexander-daniel** [naomiaro/waveform-playlist#40]
Hey there!

I think its just a case where the transpilation didn't happen. 

I see it in the ES2015 src here:
https://github.com/naomiaro/waveform-playlist/blob/master/src/Track.js#L523

However in the transpiled `lib` after installing with `npm`, I see the following:

```
            return (0, _h2.default)('div.channel-wrapper' + audibleClass, {
                attributes: {
                    "style": 'margin-left: ' + channelMargin + 'px; height: ' + data.height * numChan + 'px;'
                } }, channelChildren);
```

Is it just a case of the transpiled code did not make it into the npm publish? 

Thanks as always!

**Comment by naomiaro** [comment]
yes it's just in master branch right now and hasn't been tagged into a release quite yet. I'm hoping to do that soon.

**Comment by alexander-daniel** [comment]
Oh, my apologies! Awesome, thanks!
