### ISSUE TITLE
Improve performance on Chrome and Firefox

### ISSUE THREAD

**Issue by faroit** [naomiaro/waveform-playlist#44]
Currently, the performance of waveform-playlist is not optimal when playing back many tracks and when using chrome or firefox instead of safari.

[For example](http://www.sisec17.audiolabs-erlangen.de/#/heatmap/1/4/2/play/18/REF) on my macbook air I almost reach 100% CPU with chrome or firefox, which results in kind of choppy animations for some users.

It turns out when I turn of the waveform rendering, CPU usage goes down to a minimum of a few percent. You can easily reproduce this by [commenting out this line](https://github.com/naomiaro/waveform-playlist/blob/13e18b8dfc6073efdc414e519b2a278db058e504/src/Playlist.js#L736). I tried to dig deeper into the animation track render code and I've managed to bring the CPU usage down by a few percent, but not as much as I hoped.

Ideally my suggestion would be to have a high performance mode that renders the track waveforms only once when the tracks are loaded and only animates the playhead while playing instead of re-rendering the waveforms to show the progress.

@naomiaro what do you think?

**Comment by naomiaro** [comment]
Yeah this is probably due to too much virtual dom calculation happening within a certain amount of time which then affects smooth animation. I think it would be best if I avoid using the full virtual dom in this rendering loop since I know the few elements that should be changing anyways and avoid the virtual dom building and diffing step.

**Comment by naomiaro** [comment]
I should check how the default virtual-dom diffs for rendering. It might be worth changing to this one https://github.com/Raynos/vdom-thunk

**Comment by faroit** [comment]
that sound interesting. I have actually no idea how this works ;-) For my site I use vue.js which actually has it's own virtual-dom implementation. So my guess it that this could make it even slower.

The react people seems to be happy with this https://github.com/Flipboard/react-canvas

I really think no redrawing the waveform but use a simpler css-based trick to show the progress would make it way faster without the need of changing too many things...

**Comment by naomiaro** [comment]
I think I'm making some improvements here while I'm working on a commissioned add on.The virtual dom rendering and diffing was no problem, I think it had to do more with event scheduling overall. Hopefully I will have something you can test out sometime soonish. How large were the tracks you're loading and what devices (specs?) were giving you problems?

**Comment by naomiaro** [comment]
I haven't noticed a huge problem beforehand like you have, so I'm wondering partly at the same time if there can be some virtual dom clashes if Vue is trying to redo stuff for this playlist on your site etc.

**Comment by faroit** [comment]
Great, thanks: down from almost 100% cpu to 70% in Chrome and from 50% to 30% in Safari. However, I guess it doesn't scale nicely enough to, lets say, have 30 tracks playing smoothly. But maybe the underlying libs and the browsers get faster... who knows? ;-)

**Comment by naomiaro** [comment]
Yeah, webaudio takes a lot of memory to load large tracks and is kind of limiting by that currently. Glad to see those reductions, Chrome is really much higher than Safari!

Maybe later I can look into reducing this more. These were some easier fixes here that I needed to make anyways so a feature I'm working on could function properly pretty much.
