### ISSUE TITLE
Question: "Rendering waveform in the fly?"

### ISSUE THREAD

**Issue by loopmode** [naomiaro/waveform-playlist#48]
Hi
I am using wavesurfer.js and it only renders the waveform once an mp3 was entirely loaded. Does this library have the same limitation? Or can it somehow render what's loaded before finishing the entire download?

**Comment by naomiaro** [comment]
No, currently it's just using the webaudio api like wavesurfer.js is. This api needs to download the entire file first before it starts to decode the audio. I'd have to look into different ways to load the audio to maybe achieve this in the future.

**Comment by loopmode** [comment]
Okay. While the feature would be great, it seems like this is out of scope and more like a separate project itself.
