### ISSUE TITLE
Stereo Panning?

### ISSUE THREAD

**Issue by sergio-rivas** [naomiaro/waveform-playlist#50]
Is there a way to work with stereo panning when using this webapp? I would love to use this for simple multi-track mixing.

**Comment by naomiaro** [comment]
No, not yet! I'd like to add this in at some point though.

**Comment by Willena** [comment]
Some time ago, in #24 somebody has introduced the fact that we could add some effects to tracks, I think it is most likely the same idea here, but for a single effect, isn't it ?

**Comment by naomiaro** [comment]
Thanks for contributing this!
