### ISSUE TITLE
Trouble Installing on CLOUD9.io Workspace

### ISSUE THREAD

**Issue by RcKPC** [naomiaro/waveform-playlist#51]
Hi,

I'm trying to put your project on a workspace on cloud9. But I can't use it. 

I explain : 

I install the node_modules and after use your command npm install waveform-playlist and the folder was created. But after I can't start the projet because I haven't got some html files. I try to move "dist" folder into the good repertory but nothing working.

I really want to install it on cloud9 for school project. So please can you help me ? 

Sorry for my bad English. 

Best Regards,

RcK.

**Comment by Willena** [comment]
Steps that I used to make it work :

1. Create an html5 workspace
2. Clone the git repository
3. Open the console and type : `npm install` in the root folder of the project
4. Install jekyll : `gem install jekyll`
5. Type `npm run build`
6. Type `npm run start`
7. Open a preview and it should work. ( Examples are working )

Hope it helped you !

**Comment by naomiaro** [comment]
I'm going to close this PR now @RcKPC 

If you still need some help here, please reopen!
