### ISSUE TITLE
Saving & Loading Playlists

### ISSUE THREAD

**Issue by ewwwgiddings** [naomiaro/waveform-playlist#54]
Is there a method developed to save and load the playlist using something like AJAX? Allowing a user without access to the server or code to upload audio in the track-drop class div, and when they refresh and/or return to the website later their edits are essentially saved? I think this would be a helpful addition.

I'm guessing this could be accomplished using AJAX by posting the data in the array that is sent to the console using playlist.getInfo() in emitter.js and then calling another AJAX function in the WaveformPlaylist.init() function that retrieves this data, that can then be loaded as an array in the playlist.load() both in web-audio-editor.js? Maybe a similar method could be used for storing that data in localStorage?

**Comment by naomiaro** [comment]
Yes, you can do this with the info from "Print playlist to console". This is essentially the options that can be passed back in when recreating the playlist.

You'll have access to the `File` object that is uploaded so you can save that on your server or some other way you think of.

[Can check the console in this example](http://naomiaro.github.io/waveform-playlist/web-audio-editor.html)

**Comment by ewwwgiddings** [comment]
Thanks for the response, the confirmation on the method, the tip, and everything. I'll give writing the specific code for this idea a shot.
