### ISSUE TITLE
Asyncronous playlist - ajax

### ISSUE THREAD

**Issue by valentix** [naomiaro/waveform-playlist#57]
Hi, if i have a dynamic playlist container. When i  refresh playlist container with another playlist trough Ajax request and i Press play, browser play old audio and new audio simoultanesly. Result is bad... There is a way to clear audiocontext and re-init new playlist class without refesh page? I have tried audiocontext.close() but After play Burton not work...

**Comment by naomiaro** [comment]
How are you loading the playlist? You can use the `clear` event to get rid of the playlist's current content before you add new tracks into it.

**Comment by naomiaro** [comment]
Something like below should be OK with loading in new tracks.

```javascript

playlist.ee.emit("clear");

playlist.load([
  {
    src: "media/audio/sonnet.mp3"
  }
]).then(function() {
  //can do stuff with the playlist.
});
```
