### ISSUE TITLE
How to re-render waveform of the track

### ISSUE THREAD

**Issue by vipullimbachiya** [naomiaro/waveform-playlist#58]
I am developing a undo/redo functionality for a player, I am able to handle almost all events except trimming, I used a method setCues and it sets perfect values but the waveform on UI does not re-render I tried all methods which I though will work but none worked, can you please help with this.

**Comment by naomiaro** [comment]
The render only happens when this is called in the `Playlist` class `this.drawRequest();`

Not quite sure how you're working with it, but you probably have to call this.

**Comment by Catsvilles** [comment]
@vipullimbachiya Hi, did you had any success with undo/redo functionality? I struggle a bit with making it happen :)
