### ISSUE TITLE
Rewind with select: scroll does not update

### ISSUE THREAD

**Issue by bend86** [naomiaro/waveform-playlist#59]
Dear,

When isAutomaticScroll = true, when the timeline is scrolled and when a "select" event is emitted to an anterior time, scroll does not update. 

Here is the code to update below to fix.(in module 59)

Thank you

_createClass(_class, [{
	    key: 'hook',
	    value: function hook(node) {
	      var playlist = this.playlist;
	      if (!playlist.isScrolling) {
	        var el = node;
	
	        if (playlist.isAutomaticScroll && playlist.isPlaying()) {
	          var rect = node.getBoundingClientRect();
	          var cursorRect = node.querySelector('.cursor').getBoundingClientRect();
	
	          if (cursorRect.right > rect.right || cursorRect.left < rect.left) { // Update is here
	          //if (cursorRect.right > rect.right) {
	            playlist.scrollLeft = playlist.playbackSeconds;
	          }
	        }
	
	        var left = (0, _conversions.secondsToPixels)(playlist.scrollLeft, playlist.samplesPerPixel, playlist.sampleRate);
	
	        el.scrollLeft = left;
	      }
	    }

**Comment by naomiaro** [comment]
Cool, thanks for this! I'll try and make a PR to the src code with this change sometime soon.

**Comment by naomiaro** [comment]
This isn't quite fixed yet.

**Comment by zhouhong** [comment]
try in this
if (playlist.isAutomaticScroll&&node.querySelector('.cursor')) {
var rect = node.getBoundingClientRect();

add the &&node.querySelector('.cursor') condition to ensure the node couldn't be null,it works fine for me now.

**Comment by ezawadzki** [comment]
@zhouhong it works for me too ! It would be cool to create a pull request.

**Comment by faroit** [comment]
@zhouhong I created a pull request.

@naomiaro it would be great to have this merged soon and make a new npm version.

**Comment by naomiaro** [comment]
hey great, thanks for this! Looks like travis is failing, maybe just because the config is outdated now, not sure. I'll try to take a look after work today.

**Comment by faroit** [comment]
@naomiaro indeed. I fixed that in #108

**Comment by naomiaro** [comment]
I've published version `3.1.0`

Thanks everyone!

**Comment by faroit** [comment]
@naomiaro thank you for your continuous effort for this project. After all those years it is still very useful for our audio research community!

**Comment by naomiaro** [comment]
Thanks @faroit , glad to hear it still helps!
