### ISSUE TITLE
Record during playback

### ISSUE THREAD

**Issue by marcomora2** [naomiaro/waveform-playlist#60]
Hello, congratulations for the software, it works great! 
I'm doing some experiments trying to turn it into a small DAW: everything works (even recording with playback of other tracks) but during the playback of all tracks  I hear a substantial delay of my recording, so it's out of time compared to the other tracks.
Any idea how to handle this? Maybe are there some options to decrease  sound quality and manage the session, increasing the performance?
thank you,
ciao,
Marco

**Comment by naomiaro** [comment]
Hello, yes the recording feature isn't very polished atm. It will need some more work put into it. Unfortunately there isn't really much you can do currently to tune any performance options.
