### ISSUE TITLE
Can not hear any sound on iOS device.

### ISSUE THREAD

**Issue by HereIsPatrick** [naomiaro/waveform-playlist#61]
as title.

Do you have any idea?

**Comment by naomiaro** [comment]
What device and what iOS version is it @HereIsPatrick ?

**Comment by HereIsPatrick** [comment]
iPhone 7 / iOS 10.3.1

**Comment by naomiaro** [comment]
OK, I'll have to check. It's probably something to do with the newest version.

**Comment by naomiaro** [comment]
I've tried in the simulator and on an iPhone 6 with 10.3.1 and don't have a sound issue. Unfortunately I don't have an iPhone 7, I might be able to visit a device lab to try one.

Were you listening to the website examples @HereIsPatrick ? Which one?

**Comment by naomiaro** [comment]
I'm going to close this for now, if this is still reproducible though somehow, I will definitely look into it.
