### ISSUE TITLE
Overlapping recording

### ISSUE THREAD

**Issue by c0nstructer** [naomiaro/waveform-playlist#69]
Hi,

I think i have found a potential bug in your code, or I am doing something wrong.
Issue is occurring when new recording is being done, and it is overlapping with previous track (if there is any).
So in example, you can hear echo of previous track in new recorded track.
And if you for example record a third, you hear echoes of previous two track into third track.

Can it be separate recording for each track, without overlapping from previous ones?

**Comment by c0nstructer** [comment]
anyone?

**Comment by naomiaro** [comment]
Hey @c0nstructer , How do you record your tracks? Do you use a microphone line in? If you're using the internal microphone and listening to playback of previous tracks there's going to be a bit of echo there. 

I'm still marking recording as experiemental however, but I haven't spent too much time with overlapping multiple recorded tracks yet. I'll def try to take a look into this to see if it can be improved.

**Comment by c0nstructer** [comment]
Hi, just noticed that i was recording over laptops microphone, and it was
picking up other sounds. Thats ehy i closed.
One question: could it be set just to record without playing back other
tracks?

**Comment by naomiaro** [comment]
Aha OK. Right now there isn't an option to knot play them back automatically. They could be muted individually in the meantime.
