### ISSUE TITLE
Support Spectrogram

### ISSUE THREAD

**Issue by ritazh** [naomiaro/waveform-playlist#72]
Hi @naomiaro really awesome module. Is there any plan for adding spectrogram support? Thanks!

**Comment by naomiaro** [comment]
Hello!

I'd love to add support for a spectrogram. I'm not sure yet when I'll have time to do it, but will def keep this in mind for the upcoming months!

**Comment by entonbiba** [comment]
@naomiaro you can check out my spectrogram example for wavesurfer.js library here:
https://codepen.io/entonbiba/pen/Bpmqrq 

I'll have a look at this project and see what plugins I can add to it. +collaborator

**Comment by analyticalpicasso** [comment]
@naomiaro Hey, Thank you for this awesome module with great examples too. Is there any plan of adding spectrogram support in near future?

**Comment by naomiaro** [comment]
I've created effects capabilities in #24 which will now allow you to hook in per track or to the mastergainnode to attach any kind of webaudio node you'd like (also including Tone js). This will be released soon.

I think I'll close this issue now, as this is possible for one to build into their own playlist. I'm going to work later on in creating more of a plugin setup.
