### ISSUE TITLE
exportWorker is undefined

### ISSUE THREAD

**Issue by ALYREZA** [naomiaro/waveform-playlist#73]
this is really awesome,
but when I want to download simple file like wave,
get this error in browser console
```
TypeError: _this4.exportWorker is undefined[Learn More]  waveform-playlist.var.js:2068:12
```
I try my file in this [address](http://naomiaro.github.io/waveform-playlist/web-audio-editor.html), as you can guess everything works fine.
Thank you <3

**Comment by naomiaro** [comment]
Hello! I'm not quite sure if I understand. Are you having problems in your own setup, or does the example you linked not work for you?

The example is setup like this

https://github.com/naomiaro/waveform-playlist/blob/master/ghpages/js/web-audio-editor.js

Maybe you missed this part here?

```javascript
//initialize the WAV exporter.
playlist.initExporter();
```

**Comment by naomiaro** [comment]
@ALYREZA did this solve your issue?

**Comment by ALYREZA** [comment]
yes, thank you,
but what's the reason that some file format like wave or mp3 does not load in editor
what's the specification that certainly loaded in editor
this is loaded 
```
Channels       : 2
Sample Rate    : 44100
Precision      : 16-bit
Duration       : 00:00:12.21 = 538607 samples = 915.998 CDDA sectors
File Size      : 2.15M
Bit Rate       : 1.41M
Sample Encoding: 16-bit Signed Integer PCM
```
but this not 
```
Channels       : 2
Sample Rate    : 44100
Precision      : 32-bit
Duration       : 00:00:14.09 = 621568 samples = 1057.09 CDDA sectors
File Size      : 4.97M
Bit Rate       : 2.82M
Sample Encoding: 32-bit Signed Integer PCM
```

**Comment by naomiaro** [comment]
OK great! Glad it's working.

I'm not sure 100% of the supported file types as it will depend on what is implemented in the Web Audio API and can differ by browser and browser version.

The change from mp3 to the much larger size is that the Web Audio API will decompress your audio file when it loads and decodes the sound, so the file size will become much larger. WAV is a format that doesn't have any compression.
