### ISSUE TITLE
Display the entire track by default

### ISSUE THREAD

**Issue by ritazh** [naomiaro/waveform-playlist#74]
Sorry if I missed this in the documentation somewhere, but is there a way to configure the playlist to show the entire length of the track from start to end by default? The current behavior seems to only show a portion of the track by default unless you zoom out. Is this the expected behavior? One workaround is to adjust the zoom level depending on the track duration. But is there is recommended way to do this?

Thanks!

**Comment by naomiaro** [comment]
Hi! Yes that is the default behaviour. The tracks I have now are just 30 second slices I created from some stem samples I had.
