### ISSUE TITLE
Change Name Of Wav download file ??

### ISSUE THREAD

**Issue by DMouse123** [naomiaro/waveform-playlist#75]
Hi There, 

is there anyway to change the name of the download file ? Not just a date and time etc ?

Also at what rate are the WAV files ? 44,100 Hz ? is there anyway to change this ? Or even add MP3 ?

Thanks for your help !

Cheers
D

**Comment by naomiaro** [comment]
The name for the download is being set here:
https://github.com/naomiaro/waveform-playlist/blob/master/dist/waveform-playlist/js/emitter.js#L301

The WAV files are set to 44,100 for now. I can see if changing this will work and then make that configurable in the future. There's no encoders in the project, so the output is just WAV only for now.

**Comment by DMouse123** [comment]
Thank you ! :) Really appreciate your help ! Cheers D
