### ISSUE TITLE
Record tracks won't show in new Chrome 62

### ISSUE THREAD

**Issue by uicestone** [naomiaro/waveform-playlist#82]
Please check the demo in Chrome 62.

https://naomiaro.github.io/waveform-playlist/record.html

I can't see the record tracks, and the same happens in my project.

**Comment by naomiaro** [comment]
Hello, I've just checked in Chrome 62.0.3202.94 on my macbook air and I can record a track.

Do you have any error in the console? What kind of a device did you test on?

**Comment by uicestone** [comment]
I got no error output on first click on the record button. When I click it for a second time, I get error like this.

I'm using a MacBook Air, macOs 10.13.1, Chrome 62.0.3202.94 (64 bit)

![image](https://user-images.githubusercontent.com/2181611/33227704-670ee924-d1e4-11e7-8c4f-7e48d81c9e6a.png)

**Comment by uicestone** [comment]
I restarted Chrome then everything becomes OK.

**Comment by naomiaro** [comment]
OK, sorry about the delay, I was going to suggest that just to be sure. I've had problems with Chrome losing the ability to process sound/audio when it has been open for a very long time!
