### ISSUE TITLE
Uncaught (in promise) DOMException: Unable to decode audio data

### ISSUE THREAD

**Issue by Mehrtash3000** [naomiaro/waveform-playlist#83]
i download project from github and run with visual studio 2015
in record.html when i drag and drop mp3 file to drop zone every thing is ok.but when i use
playlist.load and add same file . i have 
Uncaught (in promise) DOMException: Unable to decode audio data
in chrome and firefox.
log is 
Track audio/BassDrums30.mp3 is in state loading
Track audio/BassDrums30.mp3 has loaded 0%
Track audio/BassDrums30.mp3 is in state decoding
and then nothing happend
please help me!

**Comment by naomiaro** [comment]
Is the file path you're loading relative to a running webserver?
