### ISSUE TITLE
[QUESTION] Saving each track.

### ISSUE THREAD

**Issue by joerichard** [naomiaro/waveform-playlist#84]
Hello,

First of all, thank you for this awesome project.

I wonder there is an easy way to get blob data from each track, so we can save each track? please give me some clue, mastah 🙏

Thank you!.

**Comment by joerichard** [comment]
Nevermind i got it, and i just want to say this is amazing project, thank you 👍

**Comment by rowild** [comment]
@joerichard for those, who also follow this project: Would you mind to post your solution?

**Comment by c0nstructer** [comment]
@joerichard  would also like to know solution.
