### ISSUE TITLE
Is it possible to use it without node?

### ISSUE THREAD

**Issue by DailySmoker** [naomiaro/waveform-playlist#87]
Hello, I found this package and it's exactly what I need for a project, but I am not using node, just plain javascript and jQuery.

Is it possibile to use it as a plugin, library without using node ?

If not, could you suggest me a library similar to this one, where I can play multiple tracks at the same time and also control them individually ? 

Thank you

**Comment by daniellizik** [comment]
you could fork the repo, change the webpack config target to `umd` and then build it yourself, or submit a PR that adds an additional UMD target webpack config

**Comment by naomiaro** [comment]
@DailySmoker yes it's totally possible, check branch gh-pages

https://github.com/naomiaro/waveform-playlist/tree/gh-pages

I don't use node for the examples.

**Comment by naomiaro** [comment]
Sorry for the late reply on this, I didn't see it until now.
