### ISSUE TITLE
Cannot export Audio using reactjs

### ISSUE THREAD

**Issue by tareq0065** [naomiaro/waveform-playlist#90]
Playlist.js:546 Uncaught (in promise) TypeError: Cannot read property 'postMessage' of undefined at Playlist.js:546

Whenever I am trying to export wav file I am getting above error. What is the solution for this?
I m using create react app.

**Comment by naomiaro** [comment]
The exporter may not have been initialised.

https://github.com/naomiaro/waveform-playlist/blob/gh-pages/js/web-audio-editor.js#L62

Do you call this?
