### ISSUE TITLE
initRecorder not working on Edge

### ISSUE THREAD

**Issue by a3626a** [naomiaro/waveform-playlist#91]
https://github.com/naomiaro/waveform-playlist/blob/0b34c18d8a6925efc4bb5956403372602b331f39/src/Playlist.js#L49-L51

`MediaRecorder` is not available on Edge.
https://caniuse.com/#feat=mediarecorder

**Comment by naomiaro** [comment]
This is only supported by a few browsers well still atm. You don't have to use the recorder part of Waveform Playlist at the moment, it's still marked as experimental because of patchy support. Just don't call `initRecorder` when instantiating the playlist.
