### ISSUE TITLE
playlist.load with absolute path

### ISSUE THREAD

**Issue by kimia000** [naomiaro/waveform-playlist#96]
If giving the absolute (instead of relative) path (in linux) to "src", it stuck at 

```
has loaded 0%
is in state decoding
```

such as

```
playlist.load([
  {
    "src": "/home/kimia/waveform-playlist-master/media/test/Song.ogg",
    "name": "Vocals"
  },
  {
    "src": "/home/kimia/waveform-playlist-master/media/test/Rhythm.ogg",
    "name": "Guitar"
  }
```
It is an issue if you want to use a file outside the program folder.

**Comment by faroit** [comment]
Is this related to a node/react  application? Have you got a solution for this? I'm stuck with the same problem. Maybe the audio loading would need to be replaced with node functions? 

@naomiaro any idea?

**Comment by naomiaro** [comment]
This path needs to be relative to a webserver for permission limitations at this time.

**Comment by naomiaro** [comment]
https://github.com/naomiaro/waveform-playlist/blob/master/src/track/loader/XHRLoader.js#L12

It takes a string, which I was using as a media file path relative to my webserver. It's possible to put some kind of http endpoint here instead though and you can then return the proper audio file you need from your webserver.
