### ISSUE TITLE
sound distorts on mobile devices when using record page

### ISSUE THREAD

**Issue by sannedubois** [naomiaro/waveform-playlist#98]
When I play music on my tablet, for example, spotify, and I open this page, the sound gets distorted. A funny but unwanted effect is that even my sony wireless headphone switches to 'ambient sound' when i visit this page. 
Also the sound of more than 4 tracks gets distorted and the browser crashes when loading more then 4 tracks.
Can we avoid this?

http://naomiaro.github.io/waveform-playlist/record.html

**Comment by joshuabenker** [comment]
@sannedubois did you managed to get the record function work on a mobile device?
because for me it doesn't work. when i go to record.html on chrome for android, the "record" button is disabled..do you have an idea what's wrong?

cheers
joshua

**Comment by sannedubois** [comment]
Hi Joshua,

Maybe you have to check if you're using https and/or check if the open
source works https://naomiaro.github.io/waveform-playlist/record.html

Best,
Derk

Op zo 17 mrt. 2019 om 16:47 schreef Joshua Benker <notifications@github.com

**Comment by naomiaro** [comment]
Yes the record function only works now on `https` connections due to changes in permissions around accessing the microphone.
